export const TABLE_ROWS = [
    {
      name: "John Michael-1",
      email: "john@creative-tim.com",
      job: "Manager",
      org: "Organization",
      online: true,
      date: "23/04/18",
    },
    {
      name: "Alexa Liras-2",
      email: "alexa@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: false,
      date: "23/04/18",
    },
    {
      name: "Laurent Perrier-3",
      email: "laurent@creative-tim.com",
      job: "Executive",
      org: "Projects",
      online: false,
      date: "19/09/17",
    },
    {
      name: "Michael Levi-4",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-5",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-6",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-7",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-8",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-9",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-10",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-11",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-12",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-13",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-14",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-15",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Michael Levi-16",
      email: "michael@creative-tim.com",
      job: "Programmer",
      org: "Developer",
      online: true,
      date: "24/12/08",
    },
    {
      name: "Richard Gran-17",
      email: "richard@creative-tim.com",
      job: "Manager",
      org: "Executive",
      online: false,
      date: "04/10/21",
    },
  ];

